server:
  port: 8090
  servlet:
    context-path: /

spring:
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 100MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
    property-naming-strategy: SNAKE_CASE

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  mapper-locations: classpath:./mapper_xml/*Mapper.xml
  type-aliases-package: com.wansentech.dao.entity
  global-config:
    id-type: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true